# pandas

- 파이썬을 활용하여 데이터 분석을 쉽게 할 수 있는 라이브러리이다.

```bash
# 파이썬의 pandas 라이브러리 설치하기
pip install pandas
```

In [1]:
# 판다스 라이브러리 불러오기
import pandas as pd

# Series

- 표 데이터의 컬럼(열)을 연상시키는 오브젝트이다.

In [ ]:
li = [10, 20, 30, 40, 50]
s1 = pd.Series(li)
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [3]:
label = ['a', 'b', 'c', 'd', 'e']
s1 = pd.Series(li, index=label)
s1

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [4]:
di = {
    'a':10,
    'b':20,
    'c':30,
    'd':40,
    'e':50
}
s1 = pd.Series(di)
s1

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [9]:
print(s1['a'])
print(s1.loc['b'])
print(s1.iloc[1])   # 절대 행번호를 지정하여 데이터에 접근하기
print(s1.iloc[-1])   # 절대 행번호를 지정하여 데이터에 접근하기

10
20
20
50

In [15]:
print(s1['a':'c'])  # a ~ c까지
print(s1['b':])     # b 부터 끝까지

print(s1.iloc[:3])  # 3은 포함되지 않음 0 ~ 2까지 

# Fancy Indexing
print(s1[['a','c','e']])
print(s1.iloc[[0, 2, 4]])

a    10
b    20
c    30
dtype: int64
b    20
c    30
d    40
e    50
dtype: int64
a    10
b    20
c    30
dtype: int64
a    10
c    30
e    50
dtype: int64
a    10
c    30
e    50
dtype: int64

In [ ]:
# Series 객체에서 자주 사용하는 속성
print(s1.values)    # 값들을 ndarray로 보여줌
print(s1.index)     # 인덱스 객체를 반환
print(s1.array)     # Numpy Extension Array 객체로 반환

[10 20 30 40 50]
Index(['a', 'b', 'c', 'd', 'e'], dtype='str')
<NumpyExtensionArray>
[10, 20, 30, 40, 50]
Length: 5, dtype: int64

In [21]:
# 값들의 수정
s1['a'] = 100
print(s1)

s1.iloc[0] = 1000
print(s1)

a    100
b     20
c     30
d     40
e     50
dtype: int64
a    1000
b      20
c      30
d      40
e      50
dtype: int64

In [ ]:
# 추가
s1['f'] = 60    # 없는 키를주어 대입하면 추가
print(s1)

a    1000
b      20
c      30
d      40
e      50
f      60
dtype: int64

In [ ]:
# 삭제
# s1에서는 삭제처리되지 않고, 삭제가 된 copy 객체를 반환해줌
s2 = s1.drop('c')
print(s2)

a    1000
b      20
d      40
e      50
f      60
dtype: int64

In [ ]:
# inplace=True를 지정하면 객체 내부의 데이터를 삭제처리한다.
s1.drop('c', inplace=True)
print(s1)

a    1000
b      20
d      40
e      50
f      60
dtype: int64

In [ ]:
# 한번에 여러개의 데이터를 삭제하기
s2 = s1.drop(['a', 'b'])
print(s2)

d    40
e    50
f    60
dtype: int64

In [ ]:
# 사칙연산을 브로드캐스팅 방식으로 지원함
# 이때 내부의 데이터를 변경하지 않고 연산된 새로운 Series객체를 반환한다.
print(s1 * 10)
print(s1 - 5)

a    10000
b      200
d      400
e      500
f      600
dtype: int64
a    995
b     15
d     35
e     45
f     55
dtype: int64

In [31]:
# Filtering 
cond = s1 <= 40
print(cond, type(cond))
s1[cond]

a    False
b     True
d     True
e    False
f    False
dtype: bool <class 'pandas.Series'>

b    20
d    40
dtype: int64

# DataFrame
- 2차원 형태의 데이터 셋을 다루기위한 오브젝트이다.

In [32]:
di = {
    'name':['kim', 'lee', 'park', 'choi'],
    'age':[30, 40, 50, 60],
    'score': [70, 80, 90, 100]
}

df = pd.DataFrame(di)
df

   name  age  score
0   kim   30     70
1   lee   40     80
2  park   50     90
3  choi   60    100

In [34]:
di = [
    {'name':'kim', 'age':30, 'score':70},
    {'name':'lee', 'age':40, 'score':80},
    {'name':'park', 'age':50, 'score':90},
    {'name':'choi', 'age':60, 'score':100}
]

df = pd.DataFrame(di)
df

   name  age  score
0   kim   30     70
1   lee   40     80
2  park   50     90
3  choi   60    100

In [ ]:
# 데이터프레임 객체를 엑셀 파일로 저장하기
df.to_excel('data/ex01.xlsx')   # openpyxl 모듈이 필수로 필요함

In [40]:
df.to_csv('data/ex01.csv')

In [41]:
# 데이터 불러오기
df = pd.read_csv('data/flight.csv')
df

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [42]:
# 앞부분 데이터 5행만 가져오기
df.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [ ]:
# 앞에 n개 행 확인하기
df.head(10)

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
5,5,Vistara,UK-945,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.33,1,5955
6,6,Vistara,UK-927,Delhi,Morning,zero,Morning,Mumbai,Economy,2.08,1,6060
7,7,Vistara,UK-951,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.17,1,6060
8,8,GO_FIRST,G8-334,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5954
9,9,GO_FIRST,G8-336,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5954

In [ ]:
# 가장 마지막에 5개 행 확인하기
df.tail()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [ ]:
print(list(df.columns)) # list형으로 변환
print(len(df.columns))  # 컬럼들의 개수 확인

['Unnamed: 0', 'airline', 'flight', 'source_city', 'departure_time', 'stops', 'arrival_time', 'destination_city', 'class', 'duration', 'days_left', 'price']
12

In [48]:
# 데이터의 기본정보 확인하기
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        300153 non-null  int64
 1   airline           300153 non-null  str
 2   flight            300153 non-null  str
 3   source_city       300153 non-null  str
 4   departure_time    300153 non-null  str
 5   stops             300153 non-null  str
 6   arrival_time      300153 non-null  str
 7   destination_city  300153 non-null  str
 8   class             300153 non-null  str
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), str(8)
memory usage: 27.5 MB

In [ ]:
# 기본적인 통계치 확인하기
# 수치형 데이터만 확인할 수 있다.
df.describe()

          Unnamed: 0       duration      days_left          price
count  300153.000000  300153.000000  300153.000000  300153.000000
mean   150076.000000      12.221021      26.004751   20889.660523
std     86646.852011       7.191997      13.561004   22697.767366
min         0.000000       0.830000       1.000000    1105.000000
25%     75038.000000       6.830000      15.000000    4783.000000
50%    150076.000000      11.250000      26.000000    7425.000000
75%    225114.000000      16.170000      38.000000   42521.000000
max    300152.000000      49.830000      49.000000  123071.000000

In [50]:
# 전체 컬럼들의 통계정보 확인하기
df.describe(include='all')

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
count,300153.000000,300153,300153,300153,300153,300153,300153,300153,300153,300153.000000,300153.000000,300153.000000
unique,NaN,6,1561,6,6,3,6,6,2,NaN,NaN,NaN
top,NaN,Vistara,UK-706,Delhi,Morning,one,Night,Mumbai,Economy,NaN,NaN,NaN
freq,NaN,127859,3235,61343,71146,250863,91538,59097,206666,NaN,NaN,NaN
mean,150076.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.221021,26.004751,20889.660523
std,86646.852011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.191997,13.561004,22697.767366
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.830000,1.000000,1105.000000
25%,75038.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.830000,15.000000,4783.000000
50%,150076.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.250000,26.000000,7425.000000
75%,225114.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.170000,38.000000,42521.000000
max,300152.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.830000,49.000000,123071.000000

In [ ]:
# 앞 3개의 데이터만 확인하기
df_t.head(3)
# 뒤 10개의 데이터 확인하기
df_t.tail(10)
# 기본정보 확인하기
df_t.info()
# 컬럼과 컬럼들의 개수 출력하기
df_t.columns
len(df_t.columns)
# titanic 데이터에서 탑승객들의 평균 나이 확인하기 29.503186	
# titanic 데이터의 전체 행 개수 확인하기 (1309)

In [53]:
df_f = pd.read_csv('data/flight.csv')

In [55]:
df_t = pd.read_csv('data/titanic.csv')
df_t.describe(include='all')

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
count,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.0,1309.0,1309.0,1309.0,1309.0,...,1309.0,1309.0,1309.0,1309.000000,1309.0,1309.0,1307.000000,1309.0,1309.0,1309.000000
mean,655.000000,29.503186,33.281086,0.355997,0.498854,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.294882,0.0,0.0,1.492731,0.0,0.0,0.261268
std,378.020061,12.905241,51.741500,0.478997,1.041658,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.837836,0.0,0.0,0.814626,0.0,0.0,0.439494
min,1.000000,0.170000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.000000,0.0,0.0,0.000000,0.0,0.0,0.000000
25%,328.000000,22.000000,7.895800,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.000000,0.0,0.0,1.000000,0.0,0.0,0.000000
50%,655.000000,28.000000,14.454200,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,0.000000
75%,982.000000,35.000000,31.275000,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,1.000000
max,1309.000000,80.000000,512.329200,1.000000,8.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,1.000000

In [56]:
df_t.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Passengerid  1309 non-null   int64
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64
 4   sibsp        1309 non-null   int64
 5   zero         1309 non-null   int64
 6   zero.1       1309 non-null   int64
 7   zero.2       1309 non-null   int64
 8   zero.3       1309 non-null   int64
 9   zero.4       1309 non-null   int64
 10  zero.5       1309 non-null   int64
 11  zero.6       1309 non-null   int64
 12  Parch        1309 non-null   int64
 13  zero.7       1309 non-null   int64
 14  zero.8       1309 non-null   int64
 15  zero.9       1309 non-null   int64
 16  zero.10      1309 non-null   int64
 17  zero.11      1309 non-null   int64
 18  zero.12      1309 non-null   int64
 19  zero.13      1309 non-null   int64
 20  zero.14      1309 non-null   int64
 21  Pclass       1309 non-null   int64
 22  zero.15      1309 non-null   int64
 23  zero.16      1309 non-null   int64
 24  Embarked     1307 non-null   float64
 25  zero.17      1309 non-null   int64
 26  zero.18      1309 non-null   int64
 27  2urvived     1309 non-null   int64
dtypes: float64(3), int64(25)
memory usage: 286.5 KB

In [57]:
# titanic 데이터에서 Pclass 컬럼의 데이터 종류의 개수 확인하기
df_t['Pclass']

0       3
1       1
2       3
3       1
4       3
       ..
1304    3
1305    1
1306    3
1307    3
1308    3
Name: Pclass, Length: 1309, dtype: int64

In [ ]:
# loc: 인덱스를 주어 하나의 행 데이터를 가져온다
df_t.loc[0]

Passengerid     1.00
Age            22.00
Fare            7.25
Sex             0.00
sibsp           1.00
zero            0.00
zero.1          0.00
zero.2          0.00
zero.3          0.00
zero.4          0.00
zero.5          0.00
zero.6          0.00
Parch           0.00
zero.7          0.00
zero.8          0.00
zero.9          0.00
zero.10         0.00
zero.11         0.00
zero.12         0.00
zero.13         0.00
zero.14         0.00
Pclass          3.00
zero.15         0.00
zero.16         0.00
Embarked        2.00
zero.17         0.00
zero.18         0.00
2urvived        0.00
Name: 0, dtype: float64

In [61]:
df_t['Pclass'].value_counts()

Pclass
3    709
1    323
2    277
Name: count, dtype: int64

In [ ]:
# 유니크한 값들을 가져온다
df_t['Pclass'].unique()

array([3, 1, 2])

In [ ]:
# 유니크한 값들의 개수를 가져온다
df_t['Pclass'].nunique()

3

In [ ]:
# 컬럼들간의 상관관계를 보여줌
df_f.corr(numeric_only=True)

            Unnamed: 0  duration  days_left     price
Unnamed: 0    1.000000  0.159007   0.014638  0.761177
duration      0.159007  1.000000  -0.039157  0.204222
days_left     0.014638 -0.039157   1.000000 -0.091949
price         0.761177  0.204222  -0.091949  1.000000

In [3]:
import pandas as pd

In [5]:
# data/flight.csv 파일을 로드하여 DataFrame객체로 생성하기
df = pd.read_csv('data/flight.csv')
# 상위 5개 데이터 확인하기
df.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [6]:
# 하위 5개 데이터 확인하기
df.tail()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [7]:
# 데이터프레임의 컬럼 및 행수 그리고 결측치 정보등의 기본정보 확인하기
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        300153 non-null  int64
 1   airline           300153 non-null  str
 2   flight            300153 non-null  str
 3   source_city       300153 non-null  str
 4   departure_time    300153 non-null  str
 5   stops             300153 non-null  str
 6   arrival_time      300153 non-null  str
 7   destination_city  300153 non-null  str
 8   class             300153 non-null  str
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), str(8)
memory usage: 27.5 MB

In [8]:
# 수치형 데이터들의 기본 통계정보 확인하기
df.describe()

          Unnamed: 0       duration      days_left          price
count  300153.000000  300153.000000  300153.000000  300153.000000
mean   150076.000000      12.221021      26.004751   20889.660523
std     86646.852011       7.191997      13.561004   22697.767366
min         0.000000       0.830000       1.000000    1105.000000
25%     75038.000000       6.830000      15.000000    4783.000000
50%    150076.000000      11.250000      26.000000    7425.000000
75%    225114.000000      16.170000      38.000000   42521.000000
max    300152.000000      49.830000      49.000000  123071.000000

In [9]:
# 문자열 데이터들을 포함한 모든 컬럼들의 통계정보 확인하기
df.describe(include='all')

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
count,300153.000000,300153,300153,300153,300153,300153,300153,300153,300153,300153.000000,300153.000000,300153.000000
unique,NaN,6,1561,6,6,3,6,6,2,NaN,NaN,NaN
top,NaN,Vistara,UK-706,Delhi,Morning,one,Night,Mumbai,Economy,NaN,NaN,NaN
freq,NaN,127859,3235,61343,71146,250863,91538,59097,206666,NaN,NaN,NaN
mean,150076.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.221021,26.004751,20889.660523
std,86646.852011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.191997,13.561004,22697.767366
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.830000,1.000000,1105.000000
25%,75038.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.830000,15.000000,4783.000000
50%,150076.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.250000,26.000000,7425.000000
75%,225114.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.170000,38.000000,42521.000000
max,300152.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.830000,49.000000,123071.000000

In [11]:
# 각 컬럼들의 상관관계를 확인하기
df.corr(numeric_only=True)

            Unnamed: 0  duration  days_left     price
Unnamed: 0    1.000000  0.159007   0.014638  0.761177
duration      0.159007  1.000000  -0.039157  0.204222
days_left     0.014638 -0.039157   1.000000 -0.091949
price         0.761177  0.204222  -0.091949  1.000000

In [14]:
# 컬럼별 데이터 가져오기
df['airline']
print(df['airline'], type(df['airline']))

0         SpiceJet
1         SpiceJet
2          AirAsia
3          Vistara
4          Vistara
            ...
300148     Vistara
300149     Vistara
300150     Vistara
300151     Vistara
300152     Vistara
Name: airline, Length: 300153, dtype: str <class 'pandas.Series'>

In [ ]:
# 특정 컬럼의 특정 행 데이터 가져오기
df['airline'][2]
df['airline'].iloc[2]   # 행번호 2에 해당하는 데이터 가져오기
df['airline'].iloc[:2]   # 행번호 2에 해당하는 데이터 가져오기, 2번에 해당하는 행 포함안됨
df['airline'].loc[:2]   # 인덱스 2번에 해당하는 행 데이터 포함

0    SpiceJet
1    SpiceJet
2     AirAsia
Name: airline, dtype: str

In [15]:
# 다중 컬럼 데이터 가져오기
df_c = df[['airline', 'duration', 'price']]
print(type(df_c))

<class 'pandas.DataFrame'>

In [26]:
df_c.loc[0]
df_c.iloc[0]

print(df_c.loc[2:4])
print()
print(df_c.iloc[2:4])

   airline  duration  price
2  AirAsia      2.17   5956
3  Vistara      2.25   5955
4  Vistara      2.33   5955

   airline  duration  price
2  AirAsia      2.17   5956
3  Vistara      2.25   5955

In [54]:
# 특정 컬럼의 데이터 타입 확인하기
print(df['airline'].dtype)

str

In [ ]:
# 범주형 데이터 확인하기
print(df['airline'].value_counts())

airline
Vistara      127859
Air_India     80892
Indigo        43120
GO_FIRST      23173
AirAsia       16098
SpiceJet       9011
Name: count, dtype: int64

In [30]:
print(df['flight'].value_counts())

flight
UK-706     3235
UK-772     2741
UK-720     2650
UK-836     2542
UK-822     2468
           ...
6E-6474       1
G8-405        1
6E-543        1
SG-1058       1
6E-3211       1
Name: count, Length: 1561, dtype: int64

In [ ]:
print(df['flight'].unique())    # 유니크한 데이터들을 리스트 형태로 반환
print(df['flight'].nunique())   # 유니크한 데이터들의 개수를 반환

<StringArray>
['SG-8709', 'SG-8157',  'I5-764',  'UK-995',  'UK-963',  'UK-945',  'UK-927',
  'UK-951',  'G8-334',  'G8-336',
 ...
  '6E-804', '6E-7183', 'SG-6017', '6E-7208', '6E-7252', '6E-7141',  '6E-557',
 '6E-7127', '6E-7259',  'AI-433']
Length: 1561, dtype: str
1561

In [39]:
# 
print(type(df.loc[1]))
df.loc[1]
# print(df.loc[1]['source_city'])
# print(df.loc[1].loc['price'])
# # iloc 를 이용하여 'price'정보 가져오기
print(df.loc[1].iloc[-1])

<class 'pandas.Series'>
5953

In [44]:
df_t = df.loc[1:3]
df_t[['departure_time', 'stops', 'arrival_time']]

  departure_time stops   arrival_time
1  Early_Morning  zero        Morning
2  Early_Morning  zero  Early_Morning
3        Morning  zero      Afternoon

In [45]:
df.loc[1:3][['departure_time', 'stops', 'arrival_time']]

  departure_time stops   arrival_time
1  Early_Morning  zero        Morning
2  Early_Morning  zero  Early_Morning
3        Morning  zero      Afternoon

In [46]:
df[['departure_time', 'stops', 'arrival_time']].loc[1:3]

  departure_time stops   arrival_time
1  Early_Morning  zero        Morning
2  Early_Morning  zero  Early_Morning
3        Morning  zero      Afternoon

In [47]:
df.loc[1:3, ['airline', 'stops']]

    airline stops
1  SpiceJet  zero
2   AirAsia  zero
3   Vistara  zero

In [51]:
df.iloc[1:4][['airline', 'stops']]

    airline stops
1  SpiceJet  zero
2   AirAsia  zero
3   Vistara  zero

In [52]:
df.head(1)

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953

In [53]:
df.iloc[1:4, [1, 5]]

    airline stops
1  SpiceJet  zero
2   AirAsia  zero
3   Vistara  zero