In [5]:
import pandas as pd
import numpy as np

# 랜덤 초기화
np.random.seed(42)

In [9]:
def make_korean_name():
    sir = ['강', '고', '곽', '구', '권', '금', '기', '김', '남', '남궁',
    '노', '도', '류', '문', '민', '박', '배', '백', '변', '서',
    '성', '손', '송', '신', '심', '안', '양', '엄', '여', '오',
    '우', '원', '유', '윤', '이', '임', '장', '전', '정', '제갈',
    '조', '주', '지', '진', '채', '최', '태', '하', '한', '허',
    '홍', '황', '황보']

    name = [
    '민', '서', '준', '도', '윤', '시', '우', '하', '은', '지',
    '현', '우', '진', '연', '아', '예', '수', '호', '태', '영',
    '재', '정', '성', '승', '동', '민', '채', '원', '린', '유',
    '빈', '안', '안', '솔', '나', '다', '라', '미', '주', '소',
    '희', '경', '혜', '선', '미', '진', '효', '훈', '석', '철',
    '건', '찬', '환', '겸', '웅', '혁', '엽', '율', '안', '온']

    arr_sir = np.array(sir)
    arr_name = np.array(name)

    return np.random.choice(arr_sir) + np.random.choice(arr_name) + np.random.choice(arr_name)

In [10]:
names = [ make_korean_name() for _ in range(100) ]
print(names)

['정찬린', '민혜하', '성주율', '변성현', '노승환', '임소승', '곽정환', '고승선', '오미서', '성안우', '손선동', '한채안', '주원온', '박아효', '홍선웅', '황엽준', '장건우', '성은주', '백도동', '문철율', '남민환', '고영원', '태온우', '진하효', '이연수', '임철소', '구서시', '주도겸', '여호민', '진솔지', '임연빈', '하아하', '문성온', '제갈재예', '채호효', '황보승민', '심온온', '채희린', '민미민', '심우은', '신민선', '김승현', '홍수하', '이나안', '권경주', '조원우', '남하우', '윤안훈', '송승라', '이선소', '손채나', '강나라', '태연준', '강윤민', '문주채', '남아아', '안경온', '류건안', '정석찬', '원도유', '장성주', '채아혜', '여다진', '원우안', '홍정원', '고경미', '황보시원', '엄선선', '서유현', '엄동주', '유민엽', '양엽찬', '류희준', '정시하', '양은라', '유건경', '진승아', '원안승', '조찬석', '한율찬', '도주서', '곽석라', '한혁수', '한서서', '엄겸성', '장안안', '강태서', '황보선민', '원시안', '구웅현', '배미승', '권찬솔', '금정현', '하예안', '남온안', '금예린', '곽영온', '임태민', '곽태영', '원우찬']

In [11]:
di = {
    '번호': np.arange(1, 101), # 1 ~ 100까지 순차적인 값들의 배열 생성
    '이름': names,
    '학년': 3,
    '반': np.random.randint(1, 6, size=100),    # 1 ~ 5까지 100개의 데이터 생성
    '국어': np.clip(np.round(np.random.normal(50, 10, size=100),2), 0, 100),
    '수학': np.clip(np.round(np.random.normal(60, 10, size=100),2), 0, 100),
    '영어': np.clip(np.round(np.random.normal(70, 10, size=100),2), 0, 100),
}

df = pd.DataFrame(di)
df

     번호   이름  학년  반     국어     수학     영어
0     1  정찬린   3  1  50.58  68.13  68.85
1     2  민혜하   3  1  38.57  66.30  82.38
2     3  성주율   3  2  53.58  51.71  54.06
3     4  변성현   3  1  55.61  54.40  64.01
4     5  노승환   3  3  60.83  67.47  70.05
..  ...  ...  .. ..    ...    ...    ...
95   96  금예린   3  1  58.50  78.31  61.39
96   97  곽영온   3  2  53.57  71.79  85.23
97   98  임태민   3  2  43.07  55.31  75.39
98   99  곽태영   3  3  59.00  42.87  59.63
99  100  원우찬   3  2  53.07  73.54  68.10

[100 rows x 7 columns]

In [12]:
# 필터링 하기
cond = df['수학'] > 100.0
df[cond]

Empty DataFrame
Columns: [번호, 이름, 학년, 반, 국어, 수학, 영어]
Index: []

In [13]:
# 국어 60점 이상, 영어 80점이상인 학생들만 가져오기
cond = (df['국어'] >= 60) & (df['영어'] >= 70)
df[cond]

    번호   이름  학년  반     국어     수학     영어
4    5  노승환   3  3  60.83  67.47  70.05
5    6  임소승   3  4  60.54  66.10  70.47
11  12  한채안   3  4  88.53  57.98  75.14
22  23  태온우   3  3  73.15  60.97  90.61
27  28  주도겸   3  3  60.89  47.86  83.69
36  37  심온온   3  1  71.44  69.75  85.02
55  56  남아아   3  4  60.32  58.40  75.04
68  69  서유현   3  4  66.32  62.24  76.14

In [14]:
# 데이터 추가하기
# 총점이라는 데이터를 생성하여 컬럼을 추가함
df['총점'] = df['국어'] + df['수학'] + df['영어']
df['평균'] = (df['총점'] / 3).round(2)
df.head()

   번호   이름  학년  반     국어     수학     영어      총점     평균
0   1  정찬린   3  1  50.58  68.13  68.85  187.56  62.52
1   2  민혜하   3  1  38.57  66.30  82.38  187.25  62.42
2   3  성주율   3  2  53.58  51.71  54.06  159.35  53.12
3   4  변성현   3  1  55.61  54.40  64.01  174.02  58.01
4   5  노승환   3  3  60.83  67.47  70.05  198.35  66.12

In [15]:
# 100명 전체의 등수 구하기
df['전체등수'] = df['총점'].rank(ascending=False).astype(int)
df.head()

   번호   이름  학년  반     국어     수학     영어      총점     평균  전체등수
0   1  정찬린   3  1  50.58  68.13  68.85  187.56  62.52    35
1   2  민혜하   3  1  38.57  66.30  82.38  187.25  62.42    36
2   3  성주율   3  2  53.58  51.71  54.06  159.35  53.12    91
3   4  변성현   3  1  55.61  54.40  64.01  174.02  58.01    65
4   5  노승환   3  3  60.83  67.47  70.05  198.35  66.12    13

In [16]:
# 데이터 정렬하기
df.sort_values(by='전체등수')

    번호    이름  학년  반     국어     수학      영어      총점     평균  전체등수
80  81   도주서   3  4  50.70  81.90  100.00  232.60  77.53     1
36  37   심온온   3  1  71.44  69.75   85.02  226.21  75.40     2
22  23   태온우   3  3  73.15  60.97   90.61  224.73  74.91     3
11  12   한채안   3  4  88.53  57.98   75.14  221.65  73.88     4
53  54   강윤민   3  1  59.18  74.75   79.55  213.48  71.16     5
..  ..   ...  .. ..    ...    ...     ...     ...    ...   ...
46  47   남하우   3  4  38.00  55.29   56.96  150.25  50.08    96
49  50   이선소   3  1  43.47  45.93   60.60  150.00  50.00    97
87  88  황보선민   3  4  30.48  61.50   55.78  147.76  49.25    98
73  74   정시하   3  1  35.64  64.98   46.98  147.60  49.20    99
64  65   홍정원   3  1  17.59  58.91   63.00  139.50  46.50   100

[100 rows x 10 columns]

In [17]:
# 수학 경시대회에 차출될 3인의 명단을 데이터 프레임으로 만들어 제출하세요
df_math_top3 = df.sort_values(by='수학', ascending=False).head(3)
df_math_top3

    번호   이름  학년  반     국어     수학      영어      총점     평균  전체등수
80  81  도주서   3  4  50.70  81.90  100.00  232.60  77.53     1
76  77  진승아   3  4  40.18  81.53   86.45  208.16  69.39     8
25  26  임철소   3  3  33.87  80.92   79.72  194.51  64.84    22

In [18]:
# 1반만 필터링하기
cond = df['반'] == 1
df[cond]

    번호    이름  학년  반     국어     수학     영어      총점     평균  전체등수
0    1   정찬린   3  1  50.58  68.13  68.85  187.56  62.52    35
1    2   민혜하   3  1  38.57  66.30  82.38  187.25  62.42    36
3    4   변성현   3  1  55.61  54.40  64.01  174.02  58.01    65
6    7   곽정환   3  1  36.22  59.79  65.50  161.51  53.84    85
7    8   고승선   3  1  40.62  61.17  76.23  178.02  59.34    56
13  14   박아효   3  1  61.36  70.99  58.75  191.10  63.70    30
16  17   장건우   3  1  46.85  73.05  73.32  193.22  64.41    25
18  19   백도동   3  1  42.27  66.82  85.51  194.60  64.87    21
23  24   진하효   3  1  31.33  65.95  87.55  184.83  61.61    42
24  25   이연수   3  1  56.86  51.82  67.51  176.19  58.73    59
29  30   진솔지   3  1  39.22  67.92  76.86  184.00  61.33    43
32  33   문성온   3  1  42.70  59.88  58.17  160.75  53.58    88
36  37   심온온   3  1  71.44  69.75  85.02  226.21  75.40     2
38  39   민미민   3  1  29.75  51.75  86.29  167.79  55.93    77
45  46   조원우   3  1  58.66  54.93  69.11  182.70  60.90    45
47  48   윤안훈   3  1  46.65  62.32  76.70  185.67  61.89    39
49  50   이선소   3  1  43.47  45.93  60.60  150.00  50.00    97
53  54   강윤민   3  1  59.18  74.75  79.55  213.48  71.16     5
54  55   문주채   3  1  71.22  68.58  60.14  199.94  66.65    12
64  65   홍정원   3  1  17.59  58.91  63.00  139.50  46.50   100
66  67  황보시원   3  1  47.47  66.90  68.88  183.25  61.08    44
73  74   정시하   3  1  35.64  64.98  46.98  147.60  49.20    99
74  75   양은라   3  1  61.63  74.51  54.85  190.99  63.66    31
81  82   곽석라   3  1  46.15  51.92  81.20  179.27  59.76    53
84  85   엄겸성   3  1  65.86  38.76  53.94  158.56  52.85    93
88  89   원시안   3  1  48.48  63.42  63.53  175.43  58.48    63
92  93   금정현   3  1  47.92  51.02  69.92  168.86  56.29    75
95  96   금예린   3  1  58.50  78.31  61.39  198.20  66.07    14

In [19]:
df['반'].value_counts().sort_index()

반
1    28
2    13
3    22
4    21
5    16
Name: count, dtype: int64

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   번호      100 non-null    int32
 1   이름      100 non-null    object
 2   학년      100 non-null    int64
 3   반       100 non-null    int32
 4   국어      100 non-null    float64
 5   수학      100 non-null    float64
 6   영어      100 non-null    float64
 7   총점      100 non-null    float64
 8   평균      100 non-null    float64
 9   전체등수    100 non-null    int32
dtypes: float64(5), int32(3), int64(1), object(1)
memory usage: 6.8+ KB

In [24]:
# 각 반의 국어, 수학, 영어 과목만 평균 점수 구하기

subjects = ['국어','수학','영어']
df_mean = df.groupby(by='반')[subjects].mean()
df_mean

          국어         수학         영어
반
1  48.278571  62.248571  69.490714
2  50.437692  59.961538  69.768462
3  51.660000  59.151364  69.632273
4  51.962381  63.612857  70.225714
5  50.274375  59.399375  69.854375

In [25]:
df.head()

   번호   이름  학년  반     국어     수학     영어      총점     평균  전체등수
0   1  정찬린   3  1  50.58  68.13  68.85  187.56  62.52    35
1   2  민혜하   3  1  38.57  66.30  82.38  187.25  62.42    36
2   3  성주율   3  2  53.58  51.71  54.06  159.35  53.12    91
3   4  변성현   3  1  55.61  54.40  64.01  174.02  58.01    65
4   5  노승환   3  3  60.83  67.47  70.05  198.35  66.12    13

In [ ]:
#반등수 구하기
df['반등수'] = df.groupby('반')['총점'].rank(ascending=False).astype(int)
df.head()

   번호   이름  학년  반     국어     수학     영어      총점     평균  전체등수  반등수
0   1  정찬린   3  1  50.58  68.13  68.85  187.56  62.52    35    9
1   2  민혜하   3  1  38.57  66.30  82.38  187.25  62.42    36   10
2   3  성주율   3  2  53.58  51.71  54.06  159.35  53.12    91   13
3   4  변성현   3  1  55.61  54.40  64.01  174.02  58.01    65   20
4   5  노승환   3  3  60.83  67.47  70.05  198.35  66.12    13    2

In [ ]:
#groupby의 집계함수들
df_agg = df.groupby('반')['총점'].agg(['count','mean','max','min','median']).round(2)
df_agg

# mean : 평균
# median : 오름차순으로 정렬한뒤 중앙값
# mode : 최빈값

   count    mean     max     min  median
반
1     28  180.02  226.21  139.50  182.98
2     13  180.17  210.59  159.35  180.32
3     22  180.44  224.73  157.20  179.95
4     21  185.80  232.60  147.76  182.57
5     16  179.53  209.18  161.30  175.64

In [34]:
# 각 반별 표준 편차 구하기
df_std = df.groupby(by='반')['평균'].std().round(2)
df_std

반
1    6.39
2    5.19
3    5.37
4    7.62
5    4.59
Name: 평균, dtype: float64

In [38]:
# 국어 영어 수학 총점 평균
# 전체 데이터의 기본 통계정보
cols = subjects + ['총점','평균']
#df_aggs = df.groupby(by='반')[cols]
#df_aggs.describe().round(2)
df[cols].describe()

               국어        수학          영어          총점          평균
count  100.000000  100.0000  100.000000  100.000000  100.000000
mean    50.396100   61.1005   69.770500  181.267100   60.422400
std     10.866903    8.8083   10.572829   18.009552    6.003406
min     17.590000   38.7600   46.980000  139.500000   46.500000
25%     43.302500   54.3275   61.900000  168.600000   56.202500
50%     50.670000   60.8650   69.405000  180.640000   60.215000
75%     56.815000   66.8400   76.740000  192.635000   64.215000
max     88.530000   81.9000  100.000000  232.600000   77.530000

In [ ]:
# 번호 이름 학년 반 국어 수학 영어 총점 평균 전체등수 반등수
# 데이터를 구간화 하기 : 수치형 데이터들을 특정 범위로 나누기

# 절대 범위 나누기 : S(90~100),A(80~89),B(70~79),C(60~69),D(50~59),F(~49) 등급 나누기
# 상대 범위 나누기 : 상위, 중상, 중하, 하위

#등급 부여하기 (절대 범위)
df['등급'] = pd.cut(df['평균'], # 구간화할 데이터 평균
                bins=[0,50,60,70,80,90,100], #구간화할 점수 기준
                labels=['F','D','C','B','A','S'], #부여할 데이터
                right=True
                )

df.head()

   번호   이름  학년  반     국어     수학     영어      총점     평균  전체등수  반등수 등급
0   1  정찬린   3  1  50.58  68.13  68.85  187.56  62.52    35    9  C
1   2  민혜하   3  1  38.57  66.30  82.38  187.25  62.42    36   10  C
2   3  성주율   3  2  53.58  51.71  54.06  159.35  53.12    91   13  D
3   4  변성현   3  1  55.61  54.40  64.01  174.02  58.01    65   20  D
4   5  노승환   3  3  60.83  67.47  70.05  198.35  66.12    13    2  C

In [40]:
# 상대구간 나누기
df['분위등급'] = pd.qcut(df['총점'], # 구간화할 데이터 평균
                        q=4, # 몇개 구간으로 나눌지 설정
                        labels=['하위','중하','중상','상위'] #부여할 데이터
                        )

df.head()

   번호   이름  학년  반     국어     수학     영어      총점     평균  전체등수  반등수 등급 분위등급
0   1  정찬린   3  1  50.58  68.13  68.85  187.56  62.52    35    9  C   중상
1   2  민혜하   3  1  38.57  66.30  82.38  187.25  62.42    36   10  C   중상
2   3  성주율   3  2  53.58  51.71  54.06  159.35  53.12    91   13  D   하위
3   4  변성현   3  1  55.61  54.40  64.01  174.02  58.01    65   20  D   중하
4   5  노승환   3  3  60.83  67.47  70.05  198.35  66.12    13    2  C   상위